/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo_JNIWrapper */

#ifndef _Included_demo_JNIWrapper
#define _Included_demo_JNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo_JNIWrapper
 * Method:    pax_mining_lib_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_demo_JNIWrapper_pax_1mining_1lib_1init
  (JNIEnv *, jclass);

/*
 * Class:     demo_JNIWrapper
 * Method:    pax_get_error_string
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_demo_JNIWrapper_pax_1get_1error_1string
  (JNIEnv *, jobject, jint);

/*
 * Class:     demo_JNIWrapper
 * Method:    pax_packet_mining_start
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_demo_JNIWrapper_pax_1packet_1mining_1start
  (JNIEnv *, jobject, jstring);

/*
 * Class:     demo_JNIWrapper
 * Method:    pax_packet_mining_cancel
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_demo_JNIWrapper_pax_1packet_1mining_1cancel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     demo_JNIWrapper
 * Method:    pax_packet_mining_get_status
 * Signature: (Ljava/lang/String;Ldemo/OutParams;)I
 */
JNIEXPORT jint JNICALL Java_demo_JNIWrapper_pax_1packet_1mining_1get_1status
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     demo_JNIWrapper
 * Method:    pax_packet_mining_get_query_stats
 * Signature: (Ljava/lang/String;Ldemo/PCAPMiningStats;)I
 */
JNIEXPORT jint JNICALL Java_demo_JNIWrapper_pax_1packet_1mining_1get_1query_1stats
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
