/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo_JNIWrapper */

#ifndef _Included_demo_JNIWrapper
#define _Included_demo_JNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo_JNIWrapper
 * Method:    pax_get_error_string
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_demo_JNIWrapper_pax_1get_1error_1string
  (JNIEnv *, jobject, jint);

/*
 * Class:     demo_JNIWrapper
 * Method:    packet_mining_start
 * Signature: (Ldemo/PcapParameters;)I
 */
JNIEXPORT jint JNICALL Java_demo_JNIWrapper_packet_1mining_1start
  (JNIEnv *, jobject, jobject);

/*
 * Class:     demo_JNIWrapper
 * Method:    packet_mining_cancel
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_demo_JNIWrapper_packet_1mining_1cancel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     demo_JNIWrapper
 * Method:    packet_mining_get_pcap_file_name
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_demo_JNIWrapper_packet_1mining_1get_1pcap_1file_1name
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
